<?php
// The sequence of triangle numbers is generated by adding the natural numbers. 
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
// The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.


// What is the value of the first triangle number to have over five hundred divisors?
$limit = 500;
$num = 1;
$triangleNumbers = array();
for ($i = 1; $i <= 10000000; $i++) {
    $num = $i * ($i + 1) / 2;
    $triangleNumbers[] =  $num;
    $num += 1;   

}
$max = sqrt(count($triangleNumbers));
for ($k=0; $k < $max; $k++) { 
    $divisors = 1;
    for ($j=1; $j < $triangleNumbers[$k] ; $j++) { 
        if($triangleNumbers[$k] % $j == 0){
            $divisors = $divisors + 1;
            // echo "number:".$triangleNumbers[$k]. "\n";
            // echo "Div=" .$divisors . "\n";
        }
        if($limit <= $divisors){
            echo "FOUND FIRST" . $triangleNumbers[$k];
            break 2;

        }
    }
   
}

